name: Java CI

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: giltene/setup-java@master
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
  #  - run: mkdir -p path/to/artifact
      ###      /home/runner/work/TokenShopEditor/TokenShopEditor/target/TokenShopEditor.jar
  #  - run: cat "./target/TokenShopEditor.jar" > "path/to/artifact/TokenShopEditor.jar"
  #  - uses: actions/upload-artifact@master
  #    with:
  #      name: TokenShopEditor Deployment
  #      path: path/to/artifact
